os: linux
dist: bionic
language: python
python: 3.7

install:
  - curl --silent -o 'latest_hugo' https://api.github.com/repos/gohugoio/hugo/releases/latest
  - TARGET=$(cat 'latest_hugo' | grep -o 'https\:\/\/github\.com\/gohugoio\/hugo\/releases\/download\/[v\.\d]+\/hugo\_extended_[v\.\d]+_Linux\-64bit\.deb')
  - curl -O $TARGET
  - sudo dpkg -i hugo*.deb
  - hugo version

script:
  - hugo --minify -e production

deploy:
  strategy: git
  provider: pages
  local_dir: public
  target_branch: gh-pages
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
