os: linux
dist: bionic
language: python
python: 3.7

install:
  - curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep  browser_download_url | grep Linux-64bit.deb | grep extended | cut -d '"' -f 4 | wget -i -
  - sudo dpkg -i hugo*.deb
  - hugo version

script:
  - hugo --minify -e production

deploy:
  strategy: git
  provider: pages
  local_dir: public
  target_branch: gh-pages
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
